# Generated by Django 2.0.1 on 2018-10-03 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='唯一标识')),
                ('img', models.ImageField(upload_to='img', verbose_name='图片文件(不超过3')),
                ('name', models.CharField(max_length=20, verbose_name='图片名字')),
            ],
            options={
                'verbose_name_plural': '谱例',
            },
        ),
        migrations.CreateModel(
            name='Jiaxun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='唯一标识')),
                ('chapter', models.CharField(max_length=30, verbose_name='章节')),
                ('content', models.TextField(verbose_name='具体内容')),
                ('create_time', models.DateTimeField(db_column='chapter_create_date', default=datetime.datetime.utcnow, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '家训',
            },
        ),
        migrations.CreateModel(
            name='Lineage',
            fields=[
                ('id', models.AutoField(max_length=30, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='img', verbose_name='图片文件(不超过3')),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(db_column='chapter_create_date', default=datetime.datetime.utcnow, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '世系分行字图',
            },
        ),
        migrations.CreateModel(
            name='MiContent',
            fields=[
                ('id', models.AutoField(max_length=30, primary_key=True, serialize=False)),
                ('chapter', models.CharField(max_length=10)),
                ('content', models.TextField(null=True)),
                ('create_time', models.DateTimeField(db_column='chapter_create_date', default=datetime.datetime.utcnow, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '修谱记叙章节',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '家族姓名'},
        ),
        migrations.AddField(
            model_name='user',
            name='device_create_date',
            field=models.DateTimeField(db_column='user_create_date', default=datetime.datetime.utcnow, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='girl_num',
            field=models.CharField(choices=[('壹', '壹'), ('贰', '贰'), ('叁', '叁'), ('肆', '肆'), ('伍', '伍'), ('陆', '陆'), ('柒', '柒'), ('捌', '捌'), ('玖', '玖'), ('拾', '拾'), ('拾壹', '拾壹'), ('拾贰', '拾贰'), ('拾叁', '拾叁'), ('拾肆', '拾肆'), ('拾伍', '拾伍'), ('拾陆', '拾陆'), ('拾柒', '拾柒'), ('拾捌', '拾捌'), ('拾玖', '拾玖'), ('贰拾', '贰拾')], max_length=10, null=True, verbose_name='女儿个数'),
        ),
        migrations.AddField(
            model_name='user',
            name='house',
            field=models.CharField(choices=[('壹', '壹'), ('贰', '贰'), ('叁', '叁'), ('肆', '肆'), ('伍', '伍'), ('陆', '陆'), ('柒', '柒'), ('捌', '捌'), ('玖', '玖'), ('拾', '拾'), ('拾壹', '拾壹'), ('拾贰', '拾贰'), ('拾叁', '拾叁'), ('拾肆', '拾肆'), ('拾伍', '拾伍'), ('拾陆', '拾陆'), ('拾柒', '拾柒'), ('拾捌', '拾捌'), ('拾玖', '拾玖'), ('贰拾', '贰拾')], max_length=10, null=True, verbose_name='房'),
        ),
        migrations.AddField(
            model_name='user',
            name='line_str',
            field=models.CharField(max_length=30, null=True, verbose_name='行字辈'),
        ),
        migrations.AddField(
            model_name='user',
            name='son_num',
            field=models.CharField(choices=[('壹', '壹'), ('贰', '贰'), ('叁', '叁'), ('肆', '肆'), ('伍', '伍'), ('陆', '陆'), ('柒', '柒'), ('捌', '捌'), ('玖', '玖'), ('拾', '拾'), ('拾壹', '拾壹'), ('拾贰', '拾贰'), ('拾叁', '拾叁'), ('拾肆', '拾肆'), ('拾伍', '拾伍'), ('拾陆', '拾陆'), ('拾柒', '拾柒'), ('拾捌', '拾捌'), ('拾玖', '拾玖'), ('贰拾', '贰拾')], max_length=10, null=True, verbose_name='儿子个数'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='content',
            field=models.TextField(verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='father_id',
            field=models.CharField(max_length=30, verbose_name='父名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='generation',
            field=models.CharField(choices=[('壹', '壹'), ('贰', '贰'), ('叁', '叁'), ('肆', '肆'), ('伍', '伍'), ('陆', '陆'), ('柒', '柒'), ('捌', '捌'), ('玖', '玖'), ('拾', '拾'), ('拾壹', '拾壹'), ('拾贰', '拾贰'), ('拾叁', '拾叁'), ('拾肆', '拾肆'), ('拾伍', '拾伍'), ('拾陆', '拾陆'), ('拾柒', '拾柒'), ('拾捌', '拾捌'), ('拾玖', '拾玖'), ('贰拾', '贰拾'), ('贰壹', '贰壹'), ('贰拾贰', '贰拾贰'), ('贰拾叁', '贰拾叁'), ('贰拾肆', '贰拾肆'), ('贰拾伍', '贰拾伍'), ('贰拾陆', '贰拾陆'), ('贰拾柒', '贰拾柒'), ('贰拾捌', '贰拾捌'), ('贰拾玖', '贰拾玖'), ('叁拾', '叁拾')], max_length=10, verbose_name='世'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=int),
        ),
        migrations.AlterField(
            model_name='user',
            name='line',
            field=models.CharField(choices=[('壹', '壹'), ('贰', '贰'), ('叁', '叁'), ('肆', '肆'), ('伍', '伍'), ('陆', '陆'), ('柒', '柒'), ('捌', '捌'), ('玖', '玖'), ('拾', '拾'), ('拾壹', '拾壹'), ('拾贰', '拾贰'), ('拾叁', '拾叁'), ('拾肆', '拾肆'), ('拾伍', '拾伍'), ('拾陆', '拾陆'), ('拾柒', '拾柒'), ('拾捌', '拾捌'), ('拾玖', '拾玖'), ('贰拾', '贰拾')], max_length=10, verbose_name='行'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=5, verbose_name='性别'),
        ),
    ]
