# Generated by Django 2.0.1 on 2018-01-20 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_create_date',
            field=models.DateTimeField(db_column='user_create_date', default=datetime.datetime.utcnow),
        ),
    ]
