# Generated by Django 2.0.1 on 2018-01-25 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_device_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.User'),
        ),
    ]
