# Generated by Django 2.0.1 on 2018-09-18 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180814_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineage',
            fields=[
                ('id', models.AutoField(max_length=30, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='img', verbose_name='图片文件(不超过3')),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(db_column='chapter_create_date', default=datetime.datetime.utcnow, verbose_name='创建时间')),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jiaxun',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='唯一标识'),
        ),
        migrations.AlterField(
            model_name='micontent',
            name='id',
            field=models.AutoField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=int),
        ),
    ]
